### ISSUE TITLE
[Best Practice] Can't make a devfile that will download the openapi schema and build the typescript

### ISSUE THREAD

**Issue by tomgeorge** [che-incubator/che-workspace-telemetry-client#45]
Assume you have two runtimes in a workspace, java and node.

In Java: 
running `yarn` fails because their is no `yarn`
running the javascript's `mvn install` fails because there is no node

In Node:
running `mvn install` fails because there is no maven
running `yarn` fails because it doesn't yet have a copy of the OpenAPI schema

Is the solution to this to just make my own image that has nodejs and maven inside of it?

cc @ibuziuk @davidfestal

**Comment by davidfestal** [comment]
cc @l0rd

**Comment by l0rd** [comment]
Yes. The best practice should be to create your command line tooling container that has all the tools you need for your build.

**Comment by tomgeorge** [comment]
Thank you!
